# Use postgres/example user/password credentials

services:
  db:
    image: postgres:16.4
    restart: always
    env_file: .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5432:5432'
